# name: Hello World
# on: [push,workflow_dispatch]
# jobs:
#     test:
#       runs-on: ununtu-latest
#       steps:
#         - name: Get Code
#         - uses: actions/checkout@v4
#         - name: install python
#         - uses: actions/setup-python@v5
#           with:
#            python-version: '3.12'
#         - name: Install dependencies
#           run: pip install -r requirements.txt
name: Hello World
on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest  # Fixed typo

    steps:
      - name: Get Code
        uses: actions/checkout@v4  # Fixed indentation and removed extra '-'

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

